// <auto-generated />
using System;
using BMRM.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BMRM.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250919184228_AddPlaylistTrack")]
    partial class AddPlaylistTrack
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BMRM.Core.Shared.Models.PlaylistTrack", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyTrackId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SpotifyTrackId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("BMRM.Core.Shared.Models.Release", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genres")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotifyAlbumId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("BMRM.Core.Shared.Models.SpotifyTrack", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.ToTable("SpotifyTracks");
                });

            modelBuilder.Entity("BMRM.Core.Shared.Models.PlaylistTrack", b =>
                {
                    b.HasOne("BMRM.Core.Shared.Models.SpotifyTrack", "SpotifyTrack")
                        .WithMany("Playlists")
                        .HasForeignKey("SpotifyTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpotifyTrack");
                });

            modelBuilder.Entity("BMRM.Core.Shared.Models.SpotifyTrack", b =>
                {
                    b.HasOne("BMRM.Core.Shared.Models.Release", "Release")
                        .WithMany("Tracks")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Release");
                });

            modelBuilder.Entity("BMRM.Core.Shared.Models.Release", b =>
                {
                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("BMRM.Core.Shared.Models.SpotifyTrack", b =>
                {
                    b.Navigation("Playlists");
                });
#pragma warning restore 612, 618
        }
    }
}
